export const LOAN_APPLICATION_REPOSITORY = Symbol('LOAN_APPLICATION_REPOSITORY');
export const ADMIN_QUERY = Symbol('ADMIN_QUERY');
export const LOAN_REPOSITORY = Symbol('LOAN_REPOSITORY');
export const INSTALLMENT_REPOSITORY = Symbol('INSTALLMENT_REPOSITORY');
export const ACTIVE_LOAN_QUERY = Symbol('ACTIVE_LOAN_QUERY');
export const ADMIN_ACTIVE_LOAN_QUERY = Symbol('ADMIN_ACTIVE_LOAN_QUERY');
export const GENERATED_DOCUMENT_REPOSITORY = Symbol('GENERATED_DOCUMENT_REPOSITORY');
export const CONTRACT_STORAGE_SERVICE = Symbol('CONTRACT_STORAGE_SERVICE');
// ponytail: Placeholder tokens for PR2 — registered but unused until generation service lands.
export const GENERATE_CONTRACT_SERVICE = Symbol('GENERATE_CONTRACT_SERVICE');
export const CONTRACT_TEMPLATE_REGISTRY = Symbol('CONTRACT_TEMPLATE_REGISTRY');
